name: "publish"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            src-tauri/target/release
            src-tauri/target/debug
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.platform }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform }}-rust-

      - name: Build Tauri
        shell: pwsh
        run: |
          $env:PATH += ";$env:CARGO_HOME\bin"
          pnpm run tauri build -- --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: |
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.exe
