name: Tauri Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (format vX.Y.Z)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        args: [""]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 提取当前tag（自动触发时）或验证输入tag（手动触发时）
      - name: Validate and set tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # 验证手动输入的tag格式
            if [[ ! "${{ inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "::error::Invalid tag format. Must be vX.Y.Z"
              exit 1
            fi
            echo "value=${{ inputs.tag }}"
          else
            # 从推送的tag中提取版本
            echo "value=${GITHUB_REF#refs/tags/}"
          fi >> $GITHUB_OUTPUT

      # Node 缓存（适配 pnpm/yarn/npm，可按实际需求更改）
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      # Rust 缓存
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Tauri Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.tag.outputs.value }}
          releaseName: '${{ steps.tag.outputs.value }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
